on: [push]
name: Azure ARM Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: 'Checkout GitHub Code'
      uses: actions/checkout@v2

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        #path: ${GITHUB_WORKSPACE}/AssociateSync/Functions/
        template: D:\a\Azure-Function\Azure-Function\AssociateSync\Functions\AssociateSync\Functions\azuredeploy.json
        #parameters: storageAccountType=Standard_LRS

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
